-- Cypress Warriorz DW schema setup and ultimate player dashboard view
-- Co-authored with CoCo
-- 1. Reset and Rebuild the Database Schema
CREATE DATABASE IF NOT EXISTS CYPRESS_WARRIORZ_DW;
USE DATABASE CYPRESS_WARRIORZ_DW;

-- Drop the old schema to clear out the un-linked tables
DROP SCHEMA IF EXISTS RAW_DATA CASCADE;
CREATE SCHEMA RAW_DATA;
USE SCHEMA RAW_DATA;

-- 2. Create the Master Player Dimension
CREATE TABLE DIM_PLAYER (
    PLAYER_ID INT PRIMARY KEY,
    PLAYER_NAME VARCHAR UNIQUE,
    IS_ACTIVE BOOLEAN,
    IS_PRACTICE_LEAGUE BOOLEAN,
    FIELDING_ALIAS VARCHAR
);

-- 3. Create the Dimension Tables (The Context & Trophies)
CREATE TABLE DIM_TEAM_STATS (
    Season VARCHAR,
    Match_Type VARCHAR,
    Playoff_Round VARCHAR,
    Opponent VARCHAR,
    Match_Result VARCHAR,
    Cypress_Runs INT,
    Cypress_Wickets INT,
    Cypress_Overs FLOAT,
    Opponent_Runs INT,
    Opponent_Wickets INT,
    Opponent_Overs FLOAT,
    File_Name VARCHAR PRIMARY KEY
);

CREATE TABLE DIM_MOTM (
    Season VARCHAR,
    Match_Type VARCHAR,
    Playoff_Round VARCHAR,
    Opponent VARCHAR,
    Match_Result VARCHAR,
    Player_Name VARCHAR,
    File_Name VARCHAR,
    FOREIGN KEY (Player_Name) REFERENCES DIM_PLAYER(PLAYER_NAME),
    FOREIGN KEY (File_Name) REFERENCES DIM_TEAM_STATS(File_Name)
);

CREATE TABLE DIM_LEAGUE_AWARDS (
    Season VARCHAR,
    Award_Type VARCHAR,
    Player_Name VARCHAR,
    Stats VARCHAR,
    Opponent VARCHAR,
    Occasion VARCHAR,
    FOREIGN KEY (Player_Name) REFERENCES DIM_PLAYER(PLAYER_NAME)
);

-- 4. Create the Fact Tables (The Core Gameplay Numbers)
CREATE TABLE FACT_BATTING (
    BatsMan VARCHAR,
    "How Out" VARCHAR, 
    Runs INT,
    Balls INT,
    Fours INT,
    Sixers INT,
    Batting_Position VARCHAR,
    Season VARCHAR,
    Match_Type VARCHAR,
    Playoff_Round VARCHAR,
    Opponent VARCHAR,
    Match_Result VARCHAR,
    File_Name VARCHAR,
    FOREIGN KEY (BatsMan) REFERENCES DIM_PLAYER(PLAYER_NAME),
    FOREIGN KEY (File_Name) REFERENCES DIM_TEAM_STATS(File_Name)
);

CREATE TABLE FACT_BOWLING (
    Bowler VARCHAR,
    Overs FLOAT,
    Madiens INT,
    Runs INT,
    Wickets INT,
    Wides INT,
    "No Balls" INT,
    Hattricks INT,
    "Dot Balls" INT,
    "5_Wicket_Haul" INT,
    Season VARCHAR,
    Match_Type VARCHAR,
    Playoff_Round VARCHAR,
    Opponent VARCHAR,
    Match_Result VARCHAR,
    File_Name VARCHAR,
    FOREIGN KEY (Bowler) REFERENCES DIM_PLAYER(PLAYER_NAME),
    FOREIGN KEY (File_Name) REFERENCES DIM_TEAM_STATS(File_Name)
);

CREATE TABLE FACT_FIELDING (
    Fielder VARCHAR,
    "How Out" VARCHAR,
    BatsMan VARCHAR,
    Bowler VARCHAR,
    Season VARCHAR,
    Match_Type VARCHAR,
    Playoff_Round VARCHAR,
    Opponent VARCHAR,
    Match_Result VARCHAR,
    File_Name VARCHAR,
    FOREIGN KEY (Fielder) REFERENCES DIM_PLAYER(PLAYER_NAME),
    FOREIGN KEY (File_Name) REFERENCES DIM_TEAM_STATS(File_Name)
);

CREATE TABLE FACT_FANTASY_POINTS (
    Player_Name VARCHAR,
    Season VARCHAR,
    Match_Type VARCHAR,
    Playoff_Round VARCHAR,
    Opponent VARCHAR,
    Match_Result VARCHAR,
    Batting_Pts FLOAT,
    Bowling_Pts FLOAT,
    Fielding_Pts FLOAT,
    MOTM_Pts FLOAT,
    Total_Pts FLOAT,
    File_Name VARCHAR,
    
    -- Connecting the points directly to your Roster and Match records
    FOREIGN KEY (Player_Name) REFERENCES DIM_PLAYER(PLAYER_NAME),
    FOREIGN KEY (File_Name) REFERENCES DIM_TEAM_STATS(File_Name)
);

CREATE OR REPLACE VIEW VW_ULTIMATE_PLAYER_DASHBOARD AS

WITH All_Games AS (
    SELECT BatsMan AS Player_Name, File_Name, Match_Type FROM FACT_BATTING
    UNION
    SELECT Bowler AS Player_Name, File_Name, Match_Type FROM FACT_BOWLING
    UNION
    SELECT p.PLAYER_NAME AS Player_Name, f.File_Name, f.Match_Type 
    FROM FACT_FIELDING f JOIN DIM_PLAYER p ON f.Fielder = p.FIELDING_ALIAS
),

Games_Agg AS (
    SELECT 
        Player_Name,
        COUNT(DISTINCT CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN File_Name END) AS Career_Games_Played,
        COUNT(DISTINCT CASE WHEN Match_Type = 'Regular Season' THEN File_Name END) AS RS_Games_Played,
        COUNT(DISTINCT CASE WHEN Match_Type = 'Playoff' THEN File_Name END) AS Playoff_Games_Played,
        COUNT(DISTINCT CASE WHEN Match_Type = 'Practice' THEN File_Name END) AS Practice_Games_Played
    FROM All_Games
    GROUP BY Player_Name
),

Batting_Agg AS (
    SELECT 
        BatsMan AS Player_Name,
        
        -- OVERALL BATTING STATS
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Runs ELSE 0 END) AS Career_Runs,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Runs ELSE 0 END) AS RS_Runs,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Runs ELSE 0 END) AS Playoff_Runs,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Runs ELSE 0 END) AS Practice_Runs,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Balls ELSE 0 END) AS Career_Balls_Faced,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Balls ELSE 0 END) AS RS_Balls_Faced,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Balls ELSE 0 END) AS Playoff_Balls_Faced,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Balls ELSE 0 END) AS Practice_Balls_Faced,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Times_Dismissed,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Times_Dismissed,
        SUM(CASE WHEN Match_Type = 'Playoff' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Times_Dismissed,
        SUM(CASE WHEN Match_Type = 'Practice' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Times_Dismissed,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Runs >= 30 AND Runs < 50 THEN 1 ELSE 0 END) AS Career_30s,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Runs >= 50 AND Runs < 75 THEN 1 ELSE 0 END) AS Career_50s,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Runs >= 75 AND Runs < 100 THEN 1 ELSE 0 END) AS Career_75s,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Runs >= 100 THEN 1 ELSE 0 END) AS Career_100s,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Fours ELSE 0 END) AS Career_4s,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Sixers ELSE 0 END) AS Career_6s,
        
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Runs >= 30 AND Runs < 50 THEN 1 ELSE 0 END) AS RS_30s,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Runs >= 50 AND Runs < 75 THEN 1 ELSE 0 END) AS RS_50s,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Runs >= 75 AND Runs < 100 THEN 1 ELSE 0 END) AS RS_75s,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Runs >= 100 THEN 1 ELSE 0 END) AS RS_100s,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Fours ELSE 0 END) AS RS_4s,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Sixers ELSE 0 END) AS RS_6s,

        SUM(CASE WHEN Match_Type = 'Playoff' AND Runs >= 30 AND Runs < 50 THEN 1 ELSE 0 END) AS Playoff_30s,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Runs >= 50 AND Runs < 75 THEN 1 ELSE 0 END) AS Playoff_50s,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Runs >= 75 AND Runs < 100 THEN 1 ELSE 0 END) AS Playoff_75s,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Runs >= 100 THEN 1 ELSE 0 END) AS Playoff_100s,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Fours ELSE 0 END) AS Playoff_4s,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Sixers ELSE 0 END) AS Playoff_6s,
        
        SUM(CASE WHEN Match_Type = 'Practice' AND Runs >= 30 AND Runs < 50 THEN 1 ELSE 0 END) AS Practice_30s,
        SUM(CASE WHEN Match_Type = 'Practice' AND Runs >= 50 AND Runs < 75 THEN 1 ELSE 0 END) AS Practice_50s,
        SUM(CASE WHEN Match_Type = 'Practice' AND Runs >= 75 AND Runs < 100 THEN 1 ELSE 0 END) AS Practice_75s,
        SUM(CASE WHEN Match_Type = 'Practice' AND Runs >= 100 THEN 1 ELSE 0 END) AS Practice_100s,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Fours ELSE 0 END) AS Practice_4s,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Sixers ELSE 0 END) AS Practice_6s,

        -- DYNAMIC POSITION SPLITS (CTE)
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_Opener,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = 'Opener' THEN Runs ELSE 0 END) AS Career_Runs_Opener,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = 'Opener' THEN Balls ELSE 0 END) AS Career_Balls_Opener,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_Opener,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_1_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '1 Down' THEN Runs ELSE 0 END) AS Career_Runs_1_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '1 Down' THEN Balls ELSE 0 END) AS Career_Balls_1_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_1_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_2_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '2 Down' THEN Runs ELSE 0 END) AS Career_Runs_2_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '2 Down' THEN Balls ELSE 0 END) AS Career_Balls_2_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_2_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_3_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '3 Down' THEN Runs ELSE 0 END) AS Career_Runs_3_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '3 Down' THEN Balls ELSE 0 END) AS Career_Balls_3_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_3_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_4_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '4 Down' THEN Runs ELSE 0 END) AS Career_Runs_4_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '4 Down' THEN Balls ELSE 0 END) AS Career_Balls_4_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_4_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_5_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '5 Down' THEN Runs ELSE 0 END) AS Career_Runs_5_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '5 Down' THEN Balls ELSE 0 END) AS Career_Balls_5_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_5_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_6_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '6 Down' THEN Runs ELSE 0 END) AS Career_Runs_6_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '6 Down' THEN Balls ELSE 0 END) AS Career_Balls_6_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_6_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_7_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '7 Down' THEN Runs ELSE 0 END) AS Career_Runs_7_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '7 Down' THEN Balls ELSE 0 END) AS Career_Balls_7_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_7_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_8_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '8 Down' THEN Runs ELSE 0 END) AS Career_Runs_8_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '8 Down' THEN Balls ELSE 0 END) AS Career_Balls_8_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_8_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_9_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '9 Down' THEN Runs ELSE 0 END) AS Career_Runs_9_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '9 Down' THEN Balls ELSE 0 END) AS Career_Balls_9_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_9_Down,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_Top_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('Opener', '1 Down') THEN Runs ELSE 0 END) AS Career_Runs_Top_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('Opener', '1 Down') THEN Balls ELSE 0 END) AS Career_Balls_Top_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_Top_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_Middle_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('2 Down', '3 Down') THEN Runs ELSE 0 END) AS Career_Runs_Middle_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('2 Down', '3 Down') THEN Balls ELSE 0 END) AS Career_Balls_Middle_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_Middle_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_Late_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('4 Down', '5 Down') THEN Runs ELSE 0 END) AS Career_Runs_Late_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('4 Down', '5 Down') THEN Balls ELSE 0 END) AS Career_Balls_Late_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_Late_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Career_Innings_Tail_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Runs ELSE 0 END) AS Career_Runs_Tail_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Balls ELSE 0 END) AS Career_Balls_Tail_Order,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Career_Dismissals_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_Opener,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = 'Opener' THEN Runs ELSE 0 END) AS RS_Runs_Opener,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = 'Opener' THEN Balls ELSE 0 END) AS RS_Balls_Opener,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_Opener,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_1_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '1 Down' THEN Runs ELSE 0 END) AS RS_Runs_1_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '1 Down' THEN Balls ELSE 0 END) AS RS_Balls_1_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_1_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_2_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '2 Down' THEN Runs ELSE 0 END) AS RS_Runs_2_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '2 Down' THEN Balls ELSE 0 END) AS RS_Balls_2_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_2_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_3_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '3 Down' THEN Runs ELSE 0 END) AS RS_Runs_3_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '3 Down' THEN Balls ELSE 0 END) AS RS_Balls_3_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_3_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_4_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '4 Down' THEN Runs ELSE 0 END) AS RS_Runs_4_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '4 Down' THEN Balls ELSE 0 END) AS RS_Balls_4_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_4_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_5_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '5 Down' THEN Runs ELSE 0 END) AS RS_Runs_5_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '5 Down' THEN Balls ELSE 0 END) AS RS_Balls_5_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_5_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_6_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '6 Down' THEN Runs ELSE 0 END) AS RS_Runs_6_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '6 Down' THEN Balls ELSE 0 END) AS RS_Balls_6_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_6_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_7_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '7 Down' THEN Runs ELSE 0 END) AS RS_Runs_7_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '7 Down' THEN Balls ELSE 0 END) AS RS_Balls_7_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_7_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_8_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '8 Down' THEN Runs ELSE 0 END) AS RS_Runs_8_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '8 Down' THEN Balls ELSE 0 END) AS RS_Balls_8_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_8_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_9_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '9 Down' THEN Runs ELSE 0 END) AS RS_Runs_9_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '9 Down' THEN Balls ELSE 0 END) AS RS_Balls_9_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_9_Down,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_Top_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('Opener', '1 Down') THEN Runs ELSE 0 END) AS RS_Runs_Top_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('Opener', '1 Down') THEN Balls ELSE 0 END) AS RS_Balls_Top_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_Top_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('2 Down', '3 Down') THEN Runs ELSE 0 END) AS RS_Runs_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('2 Down', '3 Down') THEN Balls ELSE 0 END) AS RS_Balls_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_Late_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('4 Down', '5 Down') THEN Runs ELSE 0 END) AS RS_Runs_Late_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('4 Down', '5 Down') THEN Balls ELSE 0 END) AS RS_Balls_Late_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_Late_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS RS_Innings_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Runs ELSE 0 END) AS RS_Runs_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Balls ELSE 0 END) AS RS_Balls_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS RS_Dismissals_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_Opener,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = 'Opener' THEN Runs ELSE 0 END) AS Playoff_Runs_Opener,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = 'Opener' THEN Balls ELSE 0 END) AS Playoff_Balls_Opener,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_Opener,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_1_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '1 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_1_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '1 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_1_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_1_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_2_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '2 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_2_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '2 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_2_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_2_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_3_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '3 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_3_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '3 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_3_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_3_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_4_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '4 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_4_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '4 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_4_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_4_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_5_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '5 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_5_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '5 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_5_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_5_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_6_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '6 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_6_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '6 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_6_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_6_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_7_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '7 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_7_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '7 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_7_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_7_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_8_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '8 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_8_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '8 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_8_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_8_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_9_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '9 Down' THEN Runs ELSE 0 END) AS Playoff_Runs_9_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '9 Down' THEN Balls ELSE 0 END) AS Playoff_Balls_9_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_9_Down,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_Top_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('Opener', '1 Down') THEN Runs ELSE 0 END) AS Playoff_Runs_Top_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('Opener', '1 Down') THEN Balls ELSE 0 END) AS Playoff_Balls_Top_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_Top_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('2 Down', '3 Down') THEN Runs ELSE 0 END) AS Playoff_Runs_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('2 Down', '3 Down') THEN Balls ELSE 0 END) AS Playoff_Balls_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_Late_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('4 Down', '5 Down') THEN Runs ELSE 0 END) AS Playoff_Runs_Late_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('4 Down', '5 Down') THEN Balls ELSE 0 END) AS Playoff_Balls_Late_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_Late_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Playoff_Innings_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Runs ELSE 0 END) AS Playoff_Runs_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Balls ELSE 0 END) AS Playoff_Balls_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Playoff' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Playoff_Dismissals_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_Opener,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = 'Opener' THEN Runs ELSE 0 END) AS Practice_Runs_Opener,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = 'Opener' THEN Balls ELSE 0 END) AS Practice_Balls_Opener,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = 'Opener' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_Opener,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_1_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '1 Down' THEN Runs ELSE 0 END) AS Practice_Runs_1_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '1 Down' THEN Balls ELSE 0 END) AS Practice_Balls_1_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '1 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_1_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_2_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '2 Down' THEN Runs ELSE 0 END) AS Practice_Runs_2_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '2 Down' THEN Balls ELSE 0 END) AS Practice_Balls_2_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '2 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_2_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_3_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '3 Down' THEN Runs ELSE 0 END) AS Practice_Runs_3_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '3 Down' THEN Balls ELSE 0 END) AS Practice_Balls_3_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '3 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_3_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_4_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '4 Down' THEN Runs ELSE 0 END) AS Practice_Runs_4_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '4 Down' THEN Balls ELSE 0 END) AS Practice_Balls_4_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '4 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_4_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_5_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '5 Down' THEN Runs ELSE 0 END) AS Practice_Runs_5_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '5 Down' THEN Balls ELSE 0 END) AS Practice_Balls_5_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '5 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_5_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_6_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '6 Down' THEN Runs ELSE 0 END) AS Practice_Runs_6_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '6 Down' THEN Balls ELSE 0 END) AS Practice_Balls_6_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '6 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_6_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_7_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '7 Down' THEN Runs ELSE 0 END) AS Practice_Runs_7_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '7 Down' THEN Balls ELSE 0 END) AS Practice_Balls_7_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '7 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_7_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_8_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '8 Down' THEN Runs ELSE 0 END) AS Practice_Runs_8_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '8 Down' THEN Balls ELSE 0 END) AS Practice_Balls_8_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '8 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_8_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_9_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '9 Down' THEN Runs ELSE 0 END) AS Practice_Runs_9_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '9 Down' THEN Balls ELSE 0 END) AS Practice_Balls_9_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position = '9 Down' AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_9_Down,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_Top_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('Opener', '1 Down') THEN Runs ELSE 0 END) AS Practice_Runs_Top_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('Opener', '1 Down') THEN Balls ELSE 0 END) AS Practice_Balls_Top_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('Opener', '1 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_Top_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('2 Down', '3 Down') THEN Runs ELSE 0 END) AS Practice_Runs_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('2 Down', '3 Down') THEN Balls ELSE 0 END) AS Practice_Balls_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('2 Down', '3 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_Middle_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_Late_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('4 Down', '5 Down') THEN Runs ELSE 0 END) AS Practice_Runs_Late_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('4 Down', '5 Down') THEN Balls ELSE 0 END) AS Practice_Balls_Late_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('4 Down', '5 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_Late_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('dnb', 'did not bat') THEN 1 ELSE 0 END) AS Practice_Innings_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Runs ELSE 0 END) AS Practice_Runs_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') THEN Balls ELSE 0 END) AS Practice_Balls_Tail_Order,
        SUM(CASE WHEN Match_Type = 'Practice' AND Batting_Position IN ('6 Down', '7 Down', '8 Down', '9 Down') AND LOWER("How Out") NOT IN ('not out', 'dnb', 'did not bat', 'rt', 'retired', '*', 'nan', '') THEN 1 ELSE 0 END) AS Practice_Dismissals_Tail_Order

    FROM FACT_BATTING
    GROUP BY BatsMan
),

Bowling_Agg AS (
    SELECT 
        Bowler AS Player_Name,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN FLOOR(Overs) * 6 + ROUND((Overs - FLOOR(Overs)) * 10) ELSE 0 END) AS Career_Balls_Bowled,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN FLOOR(Overs) * 6 + ROUND((Overs - FLOOR(Overs)) * 10) ELSE 0 END) AS RS_Balls_Bowled,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN FLOOR(Overs) * 6 + ROUND((Overs - FLOOR(Overs)) * 10) ELSE 0 END) AS Playoff_Balls_Bowled,
        SUM(CASE WHEN Match_Type = 'Practice' THEN FLOOR(Overs) * 6 + ROUND((Overs - FLOOR(Overs)) * 10) ELSE 0 END) AS Practice_Balls_Bowled,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Runs ELSE 0 END) AS Career_Runs_Conceded,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Runs ELSE 0 END) AS RS_Runs_Conceded,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Runs ELSE 0 END) AS Playoff_Runs_Conceded,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Runs ELSE 0 END) AS Practice_Runs_Conceded,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Wickets ELSE 0 END) AS Career_Wickets,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Wickets ELSE 0 END) AS RS_Wickets,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Wickets ELSE 0 END) AS Playoff_Wickets,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Wickets ELSE 0 END) AS Practice_Wickets,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Madiens ELSE 0 END) AS Career_Maidens,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN "5_Wicket_Haul" ELSE 0 END) AS Career_5_Wicket_Hauls,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Wides ELSE 0 END) AS Career_Wides,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN "No Balls" ELSE 0 END) AS Career_No_Balls,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN "Dot Balls" ELSE 0 END) AS Career_Dot_Balls,
        
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Madiens ELSE 0 END) AS RS_Maidens,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN "5_Wicket_Haul" ELSE 0 END) AS RS_5_Wicket_Hauls,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Wides ELSE 0 END) AS RS_Wides,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN "No Balls" ELSE 0 END) AS RS_No_Balls,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN "Dot Balls" ELSE 0 END) AS RS_Dot_Balls,
        
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Madiens ELSE 0 END) AS Playoff_Maidens,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN "5_Wicket_Haul" ELSE 0 END) AS Playoff_5_Wicket_Hauls,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Wides ELSE 0 END) AS Playoff_Wides,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN "No Balls" ELSE 0 END) AS Playoff_No_Balls,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN "Dot Balls" ELSE 0 END) AS Playoff_Dot_Balls,
        
        SUM(CASE WHEN Match_Type = 'Practice' THEN Madiens ELSE 0 END) AS Practice_Maidens,
        SUM(CASE WHEN Match_Type = 'Practice' THEN "5_Wicket_Haul" ELSE 0 END) AS Practice_5_Wicket_Hauls,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Wides ELSE 0 END) AS Practice_Wides,
        SUM(CASE WHEN Match_Type = 'Practice' THEN "No Balls" ELSE 0 END) AS Practice_No_Balls,
        SUM(CASE WHEN Match_Type = 'Practice' THEN "Dot Balls" ELSE 0 END) AS Practice_Dot_Balls
    FROM FACT_BOWLING
    GROUP BY Bowler
),

Fielding_Agg AS (
    SELECT 
        dp.PLAYER_NAME AS Player_Name,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND LOWER(ff."How Out") LIKE '%ctw%' THEN 1 ELSE 0 END) AS Career_WK_Catches,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND LOWER(ff."How Out") LIKE '%ctw%' THEN 1 ELSE 0 END) AS RS_WK_Catches,
        SUM(CASE WHEN Match_Type = 'Playoff' AND LOWER(ff."How Out") LIKE '%ctw%' THEN 1 ELSE 0 END) AS Playoff_WK_Catches,
        SUM(CASE WHEN Match_Type = 'Practice' AND LOWER(ff."How Out") LIKE '%ctw%' THEN 1 ELSE 0 END) AS Practice_WK_Catches,
        
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND LOWER(ff."How Out") LIKE '%st%' THEN 1 ELSE 0 END) AS Career_Stumpings,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND LOWER(ff."How Out") LIKE '%st%' THEN 1 ELSE 0 END) AS RS_Stumpings,
        SUM(CASE WHEN Match_Type = 'Playoff' AND LOWER(ff."How Out") LIKE '%st%' THEN 1 ELSE 0 END) AS Playoff_Stumpings,
        SUM(CASE WHEN Match_Type = 'Practice' AND LOWER(ff."How Out") LIKE '%st%' THEN 1 ELSE 0 END) AS Practice_Stumpings,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND (LOWER(ff."How Out") LIKE '%ro%' OR LOWER(ff."How Out") LIKE '%run%') THEN 1 ELSE 0 END) AS Career_Run_Outs,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND (LOWER(ff."How Out") LIKE '%ro%' OR LOWER(ff."How Out") LIKE '%run%') THEN 1 ELSE 0 END) AS RS_Run_Outs,
        SUM(CASE WHEN Match_Type = 'Playoff' AND (LOWER(ff."How Out") LIKE '%ro%' OR LOWER(ff."How Out") LIKE '%run%') THEN 1 ELSE 0 END) AS Playoff_Run_Outs,
        SUM(CASE WHEN Match_Type = 'Practice' AND (LOWER(ff."How Out") LIKE '%ro%' OR LOWER(ff."How Out") LIKE '%run%') THEN 1 ELSE 0 END) AS Practice_Run_Outs,

        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') AND (LOWER(ff."How Out") LIKE '%ct%' OR LOWER(ff."How Out") LIKE '%c%') AND LOWER(ff."How Out") NOT LIKE '%ctw%' THEN 1 ELSE 0 END) AS Career_Catches,
        SUM(CASE WHEN Match_Type = 'Regular Season' AND (LOWER(ff."How Out") LIKE '%ct%' OR LOWER(ff."How Out") LIKE '%c%') AND LOWER(ff."How Out") NOT LIKE '%ctw%' THEN 1 ELSE 0 END) AS RS_Catches,
        SUM(CASE WHEN Match_Type = 'Playoff' AND (LOWER(ff."How Out") LIKE '%ct%' OR LOWER(ff."How Out") LIKE '%c%') AND LOWER(ff."How Out") NOT LIKE '%ctw%' THEN 1 ELSE 0 END) AS Playoff_Catches,
        SUM(CASE WHEN Match_Type = 'Practice' AND (LOWER(ff."How Out") LIKE '%ct%' OR LOWER(ff."How Out") LIKE '%c%') AND LOWER(ff."How Out") NOT LIKE '%ctw%' THEN 1 ELSE 0 END) AS Practice_Catches
    FROM FACT_FIELDING ff
    JOIN DIM_PLAYER dp ON ff.Fielder = dp.FIELDING_ALIAS
    GROUP BY dp.PLAYER_NAME
),

Points_Agg AS (
    SELECT 
        Player_Name,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Batting_Pts ELSE 0 END) AS Career_Batting_Pts,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Bowling_Pts ELSE 0 END) AS Career_Bowling_Pts,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Fielding_Pts ELSE 0 END) AS Career_Fielding_Pts,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN MOTM_Pts ELSE 0 END) AS Career_Bonus_Pts,
        SUM(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN Total_Pts ELSE 0 END) AS Career_Total_Pts,
        
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Batting_Pts ELSE 0 END) AS RS_Batting_Pts,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Bowling_Pts ELSE 0 END) AS RS_Bowling_Pts,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Fielding_Pts ELSE 0 END) AS RS_Fielding_Pts,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN MOTM_Pts ELSE 0 END) AS RS_Bonus_Pts,
        SUM(CASE WHEN Match_Type = 'Regular Season' THEN Total_Pts ELSE 0 END) AS RS_Total_Pts,
        
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Batting_Pts ELSE 0 END) AS Playoff_Batting_Pts,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Bowling_Pts ELSE 0 END) AS Playoff_Bowling_Pts,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Fielding_Pts ELSE 0 END) AS Playoff_Fielding_Pts,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN MOTM_Pts ELSE 0 END) AS Playoff_Bonus_Pts,
        SUM(CASE WHEN Match_Type = 'Playoff' THEN Total_Pts ELSE 0 END) AS Playoff_Total_Pts,
        
        SUM(CASE WHEN Match_Type = 'Practice' THEN Batting_Pts ELSE 0 END) AS Practice_Batting_Pts,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Bowling_Pts ELSE 0 END) AS Practice_Bowling_Pts,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Fielding_Pts ELSE 0 END) AS Practice_Fielding_Pts,
        SUM(CASE WHEN Match_Type = 'Practice' THEN MOTM_Pts ELSE 0 END) AS Practice_Bonus_Pts,
        SUM(CASE WHEN Match_Type = 'Practice' THEN Total_Pts ELSE 0 END) AS Practice_Total_Pts
    FROM FACT_FANTASY_POINTS
    GROUP BY Player_Name
),

MOTM_Agg AS (
    SELECT 
        Player_Name, 
        COUNT(CASE WHEN Match_Type IN ('Regular Season', 'Playoff') THEN File_Name END) AS Career_MOTM_Awards,
        COUNT(CASE WHEN Match_Type = 'Regular Season' THEN File_Name END) AS RS_MOTM_Awards,
        COUNT(CASE WHEN Match_Type = 'Playoff' THEN File_Name END) AS Playoff_MOTM_Awards,
        COUNT(CASE WHEN Match_Type = 'Practice' THEN File_Name END) AS Practice_MOTM_Awards
    FROM DIM_MOTM
    GROUP BY Player_Name
),

Awards_Agg AS (
    SELECT 
        Player_Name, 
        LISTAGG(Award_Type || ' (' || Season || ')', ', ') AS Career_League_Awards
    FROM DIM_LEAGUE_AWARDS
    GROUP BY Player_Name
)

SELECT 
    dp.PLAYER_NAME,
    dp.IS_ACTIVE,
    
    -- === 1. CAREER BLOCK ===
    COALESCE(g.Career_Games_Played, 0) AS Career_Games_Played,
    COALESCE(bat.Career_Runs, 0) AS Career_Runs,
    COALESCE(bat.Career_Balls_Faced, 0) AS Career_Balls_Faced,
    ROUND(COALESCE(bat.Career_Runs, 0) / NULLIF(bat.Career_Balls_Faced, 0) * 100, 2) AS Career_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs, 0) / NULLIF(bat.Career_Times_Dismissed, 0), 2) AS Career_Batting_Average,
    COALESCE(bat.Career_30s, 0) AS Career_30s,
    COALESCE(bat.Career_50s, 0) AS Career_50s,
    COALESCE(bat.Career_75s, 0) AS Career_75s,
    COALESCE(bat.Career_100s, 0) AS Career_100s,
    COALESCE(bat.Career_4s, 0) AS Career_4s,
    COALESCE(bat.Career_6s, 0) AS Career_6s,

    -- DYNAMIC POSITION SPLITS (FINAL SELECT - CAREER)
    COALESCE(bat.Career_Innings_Opener, 0) AS Career_Opener_Innings,
    COALESCE(bat.Career_Runs_Opener, 0) AS Career_Opener_Runs,
    COALESCE(bat.Career_Balls_Opener, 0) AS Career_Opener_Balls,
    ROUND(COALESCE(bat.Career_Runs_Opener, 0) / NULLIF(bat.Career_Balls_Opener, 0) * 100, 2) AS Career_Opener_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_Opener, 0) / NULLIF(bat.Career_Dismissals_Opener, 0), 2) AS Career_Opener_Average,
    COALESCE(bat.Career_Innings_1_Down, 0) AS Career_1_Down_Innings,
    COALESCE(bat.Career_Runs_1_Down, 0) AS Career_1_Down_Runs,
    COALESCE(bat.Career_Balls_1_Down, 0) AS Career_1_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_1_Down, 0) / NULLIF(bat.Career_Balls_1_Down, 0) * 100, 2) AS Career_1_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_1_Down, 0) / NULLIF(bat.Career_Dismissals_1_Down, 0), 2) AS Career_1_Down_Average,
    COALESCE(bat.Career_Innings_2_Down, 0) AS Career_2_Down_Innings,
    COALESCE(bat.Career_Runs_2_Down, 0) AS Career_2_Down_Runs,
    COALESCE(bat.Career_Balls_2_Down, 0) AS Career_2_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_2_Down, 0) / NULLIF(bat.Career_Balls_2_Down, 0) * 100, 2) AS Career_2_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_2_Down, 0) / NULLIF(bat.Career_Dismissals_2_Down, 0), 2) AS Career_2_Down_Average,
    COALESCE(bat.Career_Innings_3_Down, 0) AS Career_3_Down_Innings,
    COALESCE(bat.Career_Runs_3_Down, 0) AS Career_3_Down_Runs,
    COALESCE(bat.Career_Balls_3_Down, 0) AS Career_3_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_3_Down, 0) / NULLIF(bat.Career_Balls_3_Down, 0) * 100, 2) AS Career_3_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_3_Down, 0) / NULLIF(bat.Career_Dismissals_3_Down, 0), 2) AS Career_3_Down_Average,
    COALESCE(bat.Career_Innings_4_Down, 0) AS Career_4_Down_Innings,
    COALESCE(bat.Career_Runs_4_Down, 0) AS Career_4_Down_Runs,
    COALESCE(bat.Career_Balls_4_Down, 0) AS Career_4_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_4_Down, 0) / NULLIF(bat.Career_Balls_4_Down, 0) * 100, 2) AS Career_4_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_4_Down, 0) / NULLIF(bat.Career_Dismissals_4_Down, 0), 2) AS Career_4_Down_Average,
    COALESCE(bat.Career_Innings_5_Down, 0) AS Career_5_Down_Innings,
    COALESCE(bat.Career_Runs_5_Down, 0) AS Career_5_Down_Runs,
    COALESCE(bat.Career_Balls_5_Down, 0) AS Career_5_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_5_Down, 0) / NULLIF(bat.Career_Balls_5_Down, 0) * 100, 2) AS Career_5_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_5_Down, 0) / NULLIF(bat.Career_Dismissals_5_Down, 0), 2) AS Career_5_Down_Average,
    COALESCE(bat.Career_Innings_6_Down, 0) AS Career_6_Down_Innings,
    COALESCE(bat.Career_Runs_6_Down, 0) AS Career_6_Down_Runs,
    COALESCE(bat.Career_Balls_6_Down, 0) AS Career_6_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_6_Down, 0) / NULLIF(bat.Career_Balls_6_Down, 0) * 100, 2) AS Career_6_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_6_Down, 0) / NULLIF(bat.Career_Dismissals_6_Down, 0), 2) AS Career_6_Down_Average,
    COALESCE(bat.Career_Innings_7_Down, 0) AS Career_7_Down_Innings,
    COALESCE(bat.Career_Runs_7_Down, 0) AS Career_7_Down_Runs,
    COALESCE(bat.Career_Balls_7_Down, 0) AS Career_7_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_7_Down, 0) / NULLIF(bat.Career_Balls_7_Down, 0) * 100, 2) AS Career_7_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_7_Down, 0) / NULLIF(bat.Career_Dismissals_7_Down, 0), 2) AS Career_7_Down_Average,
    COALESCE(bat.Career_Innings_8_Down, 0) AS Career_8_Down_Innings,
    COALESCE(bat.Career_Runs_8_Down, 0) AS Career_8_Down_Runs,
    COALESCE(bat.Career_Balls_8_Down, 0) AS Career_8_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_8_Down, 0) / NULLIF(bat.Career_Balls_8_Down, 0) * 100, 2) AS Career_8_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_8_Down, 0) / NULLIF(bat.Career_Dismissals_8_Down, 0), 2) AS Career_8_Down_Average,
    COALESCE(bat.Career_Innings_9_Down, 0) AS Career_9_Down_Innings,
    COALESCE(bat.Career_Runs_9_Down, 0) AS Career_9_Down_Runs,
    COALESCE(bat.Career_Balls_9_Down, 0) AS Career_9_Down_Balls,
    ROUND(COALESCE(bat.Career_Runs_9_Down, 0) / NULLIF(bat.Career_Balls_9_Down, 0) * 100, 2) AS Career_9_Down_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_9_Down, 0) / NULLIF(bat.Career_Dismissals_9_Down, 0), 2) AS Career_9_Down_Average,
    COALESCE(bat.Career_Innings_Top_Order, 0) AS Career_Top_Order_Innings,
    COALESCE(bat.Career_Runs_Top_Order, 0) AS Career_Top_Order_Runs,
    COALESCE(bat.Career_Balls_Top_Order, 0) AS Career_Top_Order_Balls,
    ROUND(COALESCE(bat.Career_Runs_Top_Order, 0) / NULLIF(bat.Career_Balls_Top_Order, 0) * 100, 2) AS Career_Top_Order_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_Top_Order, 0) / NULLIF(bat.Career_Dismissals_Top_Order, 0), 2) AS Career_Top_Order_Average,
    COALESCE(bat.Career_Innings_Middle_Order, 0) AS Career_Middle_Order_Innings,
    COALESCE(bat.Career_Runs_Middle_Order, 0) AS Career_Middle_Order_Runs,
    COALESCE(bat.Career_Balls_Middle_Order, 0) AS Career_Middle_Order_Balls,
    ROUND(COALESCE(bat.Career_Runs_Middle_Order, 0) / NULLIF(bat.Career_Balls_Middle_Order, 0) * 100, 2) AS Career_Middle_Order_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_Middle_Order, 0) / NULLIF(bat.Career_Dismissals_Middle_Order, 0), 2) AS Career_Middle_Order_Average,
    COALESCE(bat.Career_Innings_Late_Order, 0) AS Career_Late_Order_Innings,
    COALESCE(bat.Career_Runs_Late_Order, 0) AS Career_Late_Order_Runs,
    COALESCE(bat.Career_Balls_Late_Order, 0) AS Career_Late_Order_Balls,
    ROUND(COALESCE(bat.Career_Runs_Late_Order, 0) / NULLIF(bat.Career_Balls_Late_Order, 0) * 100, 2) AS Career_Late_Order_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_Late_Order, 0) / NULLIF(bat.Career_Dismissals_Late_Order, 0), 2) AS Career_Late_Order_Average,
    COALESCE(bat.Career_Innings_Tail_Order, 0) AS Career_Tail_Order_Innings,
    COALESCE(bat.Career_Runs_Tail_Order, 0) AS Career_Tail_Order_Runs,
    COALESCE(bat.Career_Balls_Tail_Order, 0) AS Career_Tail_Order_Balls,
    ROUND(COALESCE(bat.Career_Runs_Tail_Order, 0) / NULLIF(bat.Career_Balls_Tail_Order, 0) * 100, 2) AS Career_Tail_Order_Strike_Rate,
    ROUND(COALESCE(bat.Career_Runs_Tail_Order, 0) / NULLIF(bat.Career_Dismissals_Tail_Order, 0), 2) AS Career_Tail_Order_Average,

    -- Career Bowling
    FLOOR(COALESCE(bowl.Career_Balls_Bowled, 0) / 6) + (MOD(COALESCE(bowl.Career_Balls_Bowled, 0), 6) / 10.0) AS Career_Overs_Bowled,
    COALESCE(bowl.Career_Runs_Conceded, 0) AS Career_Runs_Conceded,
    COALESCE(bowl.Career_Wickets, 0) AS Career_Wickets,
    ROUND(COALESCE(bowl.Career_Runs_Conceded, 0) / NULLIF(bowl.Career_Wickets, 0), 2) AS Career_Bowling_Average,
    ROUND(COALESCE(bowl.Career_Runs_Conceded, 0) / NULLIF((bowl.Career_Balls_Bowled / 6.0), 0), 2) AS Career_Economy_Rate,
    COALESCE(bowl.Career_Maidens, 0) AS Career_Maidens,
    COALESCE(bowl.Career_5_Wicket_Hauls, 0) AS Career_5_Wicket_Hauls,
    COALESCE(bowl.Career_Wides, 0) AS Career_Wides,
    COALESCE(bowl.Career_No_Balls, 0) AS Career_No_Balls,
    COALESCE(bowl.Career_Dot_Balls, 0) AS Career_Dot_Balls,
    
    -- Career Fielding
    COALESCE(fld.Career_Catches, 0) AS Career_Catches,
    COALESCE(fld.Career_WK_Catches, 0) AS Career_WK_Catches,
    COALESCE(fld.Career_Stumpings, 0) AS Career_Stumpings,
    COALESCE(fld.Career_Run_Outs, 0) AS Career_Run_Outs,
    
    -- Career Points
    COALESCE(pts.Career_Batting_Pts, 0) AS Career_Batting_Pts,
    COALESCE(pts.Career_Bowling_Pts, 0) AS Career_Bowling_Pts,
    COALESCE(pts.Career_Fielding_Pts, 0) AS Career_Fielding_Pts,
    COALESCE(pts.Career_Bonus_Pts, 0) AS Career_Bonus_Pts,
    COALESCE(pts.Career_Total_Pts, 0) AS Career_Total_Pts,

    -- === 2. REGULAR SEASON BLOCK ===
    COALESCE(g.RS_Games_Played, 0) AS RS_Games_Played,
    COALESCE(bat.RS_Runs, 0) AS RS_Runs,
    COALESCE(bat.RS_Balls_Faced, 0) AS RS_Balls_Faced,
    ROUND(COALESCE(bat.RS_Runs, 0) / NULLIF(bat.RS_Balls_Faced, 0) * 100, 2) AS RS_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs, 0) / NULLIF(bat.RS_Times_Dismissed, 0), 2) AS RS_Batting_Average,
    COALESCE(bat.RS_30s, 0) AS RS_30s,
    COALESCE(bat.RS_50s, 0) AS RS_50s,
    COALESCE(bat.RS_75s, 0) AS RS_75s,
    COALESCE(bat.RS_100s, 0) AS RS_100s,
    COALESCE(bat.RS_4s, 0) AS RS_4s,
    COALESCE(bat.RS_6s, 0) AS RS_6s,

    -- DYNAMIC POSITION SPLITS (FINAL SELECT - RS)
    COALESCE(bat.RS_Innings_Opener, 0) AS RS_Opener_Innings,
    COALESCE(bat.RS_Runs_Opener, 0) AS RS_Opener_Runs,
    COALESCE(bat.RS_Balls_Opener, 0) AS RS_Opener_Balls,
    ROUND(COALESCE(bat.RS_Runs_Opener, 0) / NULLIF(bat.RS_Balls_Opener, 0) * 100, 2) AS RS_Opener_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_Opener, 0) / NULLIF(bat.RS_Dismissals_Opener, 0), 2) AS RS_Opener_Average,
    COALESCE(bat.RS_Innings_1_Down, 0) AS RS_1_Down_Innings,
    COALESCE(bat.RS_Runs_1_Down, 0) AS RS_1_Down_Runs,
    COALESCE(bat.RS_Balls_1_Down, 0) AS RS_1_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_1_Down, 0) / NULLIF(bat.RS_Balls_1_Down, 0) * 100, 2) AS RS_1_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_1_Down, 0) / NULLIF(bat.RS_Dismissals_1_Down, 0), 2) AS RS_1_Down_Average,
    COALESCE(bat.RS_Innings_2_Down, 0) AS RS_2_Down_Innings,
    COALESCE(bat.RS_Runs_2_Down, 0) AS RS_2_Down_Runs,
    COALESCE(bat.RS_Balls_2_Down, 0) AS RS_2_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_2_Down, 0) / NULLIF(bat.RS_Balls_2_Down, 0) * 100, 2) AS RS_2_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_2_Down, 0) / NULLIF(bat.RS_Dismissals_2_Down, 0), 2) AS RS_2_Down_Average,
    COALESCE(bat.RS_Innings_3_Down, 0) AS RS_3_Down_Innings,
    COALESCE(bat.RS_Runs_3_Down, 0) AS RS_3_Down_Runs,
    COALESCE(bat.RS_Balls_3_Down, 0) AS RS_3_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_3_Down, 0) / NULLIF(bat.RS_Balls_3_Down, 0) * 100, 2) AS RS_3_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_3_Down, 0) / NULLIF(bat.RS_Dismissals_3_Down, 0), 2) AS RS_3_Down_Average,
    COALESCE(bat.RS_Innings_4_Down, 0) AS RS_4_Down_Innings,
    COALESCE(bat.RS_Runs_4_Down, 0) AS RS_4_Down_Runs,
    COALESCE(bat.RS_Balls_4_Down, 0) AS RS_4_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_4_Down, 0) / NULLIF(bat.RS_Balls_4_Down, 0) * 100, 2) AS RS_4_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_4_Down, 0) / NULLIF(bat.RS_Dismissals_4_Down, 0), 2) AS RS_4_Down_Average,
    COALESCE(bat.RS_Innings_5_Down, 0) AS RS_5_Down_Innings,
    COALESCE(bat.RS_Runs_5_Down, 0) AS RS_5_Down_Runs,
    COALESCE(bat.RS_Balls_5_Down, 0) AS RS_5_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_5_Down, 0) / NULLIF(bat.RS_Balls_5_Down, 0) * 100, 2) AS RS_5_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_5_Down, 0) / NULLIF(bat.RS_Dismissals_5_Down, 0), 2) AS RS_5_Down_Average,
    COALESCE(bat.RS_Innings_6_Down, 0) AS RS_6_Down_Innings,
    COALESCE(bat.RS_Runs_6_Down, 0) AS RS_6_Down_Runs,
    COALESCE(bat.RS_Balls_6_Down, 0) AS RS_6_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_6_Down, 0) / NULLIF(bat.RS_Balls_6_Down, 0) * 100, 2) AS RS_6_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_6_Down, 0) / NULLIF(bat.RS_Dismissals_6_Down, 0), 2) AS RS_6_Down_Average,
    COALESCE(bat.RS_Innings_7_Down, 0) AS RS_7_Down_Innings,
    COALESCE(bat.RS_Runs_7_Down, 0) AS RS_7_Down_Runs,
    COALESCE(bat.RS_Balls_7_Down, 0) AS RS_7_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_7_Down, 0) / NULLIF(bat.RS_Balls_7_Down, 0) * 100, 2) AS RS_7_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_7_Down, 0) / NULLIF(bat.RS_Dismissals_7_Down, 0), 2) AS RS_7_Down_Average,
    COALESCE(bat.RS_Innings_8_Down, 0) AS RS_8_Down_Innings,
    COALESCE(bat.RS_Runs_8_Down, 0) AS RS_8_Down_Runs,
    COALESCE(bat.RS_Balls_8_Down, 0) AS RS_8_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_8_Down, 0) / NULLIF(bat.RS_Balls_8_Down, 0) * 100, 2) AS RS_8_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_8_Down, 0) / NULLIF(bat.RS_Dismissals_8_Down, 0), 2) AS RS_8_Down_Average,
    COALESCE(bat.RS_Innings_9_Down, 0) AS RS_9_Down_Innings,
    COALESCE(bat.RS_Runs_9_Down, 0) AS RS_9_Down_Runs,
    COALESCE(bat.RS_Balls_9_Down, 0) AS RS_9_Down_Balls,
    ROUND(COALESCE(bat.RS_Runs_9_Down, 0) / NULLIF(bat.RS_Balls_9_Down, 0) * 100, 2) AS RS_9_Down_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_9_Down, 0) / NULLIF(bat.RS_Dismissals_9_Down, 0), 2) AS RS_9_Down_Average,
    COALESCE(bat.RS_Innings_Top_Order, 0) AS RS_Top_Order_Innings,
    COALESCE(bat.RS_Runs_Top_Order, 0) AS RS_Top_Order_Runs,
    COALESCE(bat.RS_Balls_Top_Order, 0) AS RS_Top_Order_Balls,
    ROUND(COALESCE(bat.RS_Runs_Top_Order, 0) / NULLIF(bat.RS_Balls_Top_Order, 0) * 100, 2) AS RS_Top_Order_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_Top_Order, 0) / NULLIF(bat.RS_Dismissals_Top_Order, 0), 2) AS RS_Top_Order_Average,
    COALESCE(bat.RS_Innings_Middle_Order, 0) AS RS_Middle_Order_Innings,
    COALESCE(bat.RS_Runs_Middle_Order, 0) AS RS_Middle_Order_Runs,
    COALESCE(bat.RS_Balls_Middle_Order, 0) AS RS_Middle_Order_Balls,
    ROUND(COALESCE(bat.RS_Runs_Middle_Order, 0) / NULLIF(bat.RS_Balls_Middle_Order, 0) * 100, 2) AS RS_Middle_Order_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_Middle_Order, 0) / NULLIF(bat.RS_Dismissals_Middle_Order, 0), 2) AS RS_Middle_Order_Average,
    COALESCE(bat.RS_Innings_Late_Order, 0) AS RS_Late_Order_Innings,
    COALESCE(bat.RS_Runs_Late_Order, 0) AS RS_Late_Order_Runs,
    COALESCE(bat.RS_Balls_Late_Order, 0) AS RS_Late_Order_Balls,
    ROUND(COALESCE(bat.RS_Runs_Late_Order, 0) / NULLIF(bat.RS_Balls_Late_Order, 0) * 100, 2) AS RS_Late_Order_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_Late_Order, 0) / NULLIF(bat.RS_Dismissals_Late_Order, 0), 2) AS RS_Late_Order_Average,
    COALESCE(bat.RS_Innings_Tail_Order, 0) AS RS_Tail_Order_Innings,
    COALESCE(bat.RS_Runs_Tail_Order, 0) AS RS_Tail_Order_Runs,
    COALESCE(bat.RS_Balls_Tail_Order, 0) AS RS_Tail_Order_Balls,
    ROUND(COALESCE(bat.RS_Runs_Tail_Order, 0) / NULLIF(bat.RS_Balls_Tail_Order, 0) * 100, 2) AS RS_Tail_Order_Strike_Rate,
    ROUND(COALESCE(bat.RS_Runs_Tail_Order, 0) / NULLIF(bat.RS_Dismissals_Tail_Order, 0), 2) AS RS_Tail_Order_Average,

    -- RS Bowling
    FLOOR(COALESCE(bowl.RS_Balls_Bowled, 0) / 6) + (MOD(COALESCE(bowl.RS_Balls_Bowled, 0), 6) / 10.0) AS RS_Overs_Bowled,
    COALESCE(bowl.RS_Runs_Conceded, 0) AS RS_Runs_Conceded,
    COALESCE(bowl.RS_Wickets, 0) AS RS_Wickets,
    ROUND(COALESCE(bowl.RS_Runs_Conceded, 0) / NULLIF(bowl.RS_Wickets, 0), 2) AS RS_Bowling_Average,
    ROUND(COALESCE(bowl.RS_Runs_Conceded, 0) / NULLIF((bowl.RS_Balls_Bowled / 6.0), 0), 2) AS RS_Economy_Rate,
    COALESCE(bowl.RS_Maidens, 0) AS RS_Maidens,
    COALESCE(bowl.RS_5_Wicket_Hauls, 0) AS RS_5_Wicket_Hauls,
    COALESCE(bowl.RS_Wides, 0) AS RS_Wides,
    COALESCE(bowl.RS_No_Balls, 0) AS RS_No_Balls,
    COALESCE(bowl.RS_Dot_Balls, 0) AS RS_Dot_Balls,
    
    -- RS Fielding
    COALESCE(fld.RS_Catches, 0) AS RS_Catches,
    COALESCE(fld.RS_WK_Catches, 0) AS RS_WK_Catches,
    COALESCE(fld.RS_Stumpings, 0) AS RS_Stumpings,
    COALESCE(fld.RS_Run_Outs, 0) AS RS_Run_Outs,
    
    -- RS Points
    COALESCE(pts.RS_Batting_Pts, 0) AS RS_Batting_Pts,
    COALESCE(pts.RS_Bowling_Pts, 0) AS RS_Bowling_Pts,
    COALESCE(pts.RS_Fielding_Pts, 0) AS RS_Fielding_Pts,
    COALESCE(pts.RS_Bonus_Pts, 0) AS RS_Bonus_Pts,
    COALESCE(pts.RS_Total_Pts, 0) AS RS_Total_Pts,

    -- === 3. PLAYOFF BLOCK ===
    COALESCE(g.Playoff_Games_Played, 0) AS Playoff_Games_Played,
    COALESCE(bat.Playoff_Runs, 0) AS Playoff_Runs,
    COALESCE(bat.Playoff_Balls_Faced, 0) AS Playoff_Balls_Faced,
    ROUND(COALESCE(bat.Playoff_Runs, 0) / NULLIF(bat.Playoff_Balls_Faced, 0) * 100, 2) AS Playoff_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs, 0) / NULLIF(bat.Playoff_Times_Dismissed, 0), 2) AS Playoff_Batting_Average,
    COALESCE(bat.Playoff_30s, 0) AS Playoff_30s,
    COALESCE(bat.Playoff_50s, 0) AS Playoff_50s,
    COALESCE(bat.Playoff_75s, 0) AS Playoff_75s,
    COALESCE(bat.Playoff_100s, 0) AS Playoff_100s,
    COALESCE(bat.Playoff_4s, 0) AS Playoff_4s,
    COALESCE(bat.Playoff_6s, 0) AS Playoff_6s,

    -- DYNAMIC POSITION SPLITS (FINAL SELECT - PLAYOFF)
    COALESCE(bat.Playoff_Innings_Opener, 0) AS Playoff_Opener_Innings,
    COALESCE(bat.Playoff_Runs_Opener, 0) AS Playoff_Opener_Runs,
    COALESCE(bat.Playoff_Balls_Opener, 0) AS Playoff_Opener_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_Opener, 0) / NULLIF(bat.Playoff_Balls_Opener, 0) * 100, 2) AS Playoff_Opener_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_Opener, 0) / NULLIF(bat.Playoff_Dismissals_Opener, 0), 2) AS Playoff_Opener_Average,
    COALESCE(bat.Playoff_Innings_1_Down, 0) AS Playoff_1_Down_Innings,
    COALESCE(bat.Playoff_Runs_1_Down, 0) AS Playoff_1_Down_Runs,
    COALESCE(bat.Playoff_Balls_1_Down, 0) AS Playoff_1_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_1_Down, 0) / NULLIF(bat.Playoff_Balls_1_Down, 0) * 100, 2) AS Playoff_1_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_1_Down, 0) / NULLIF(bat.Playoff_Dismissals_1_Down, 0), 2) AS Playoff_1_Down_Average,
    COALESCE(bat.Playoff_Innings_2_Down, 0) AS Playoff_2_Down_Innings,
    COALESCE(bat.Playoff_Runs_2_Down, 0) AS Playoff_2_Down_Runs,
    COALESCE(bat.Playoff_Balls_2_Down, 0) AS Playoff_2_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_2_Down, 0) / NULLIF(bat.Playoff_Balls_2_Down, 0) * 100, 2) AS Playoff_2_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_2_Down, 0) / NULLIF(bat.Playoff_Dismissals_2_Down, 0), 2) AS Playoff_2_Down_Average,
    COALESCE(bat.Playoff_Innings_3_Down, 0) AS Playoff_3_Down_Innings,
    COALESCE(bat.Playoff_Runs_3_Down, 0) AS Playoff_3_Down_Runs,
    COALESCE(bat.Playoff_Balls_3_Down, 0) AS Playoff_3_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_3_Down, 0) / NULLIF(bat.Playoff_Balls_3_Down, 0) * 100, 2) AS Playoff_3_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_3_Down, 0) / NULLIF(bat.Playoff_Dismissals_3_Down, 0), 2) AS Playoff_3_Down_Average,
    COALESCE(bat.Playoff_Innings_4_Down, 0) AS Playoff_4_Down_Innings,
    COALESCE(bat.Playoff_Runs_4_Down, 0) AS Playoff_4_Down_Runs,
    COALESCE(bat.Playoff_Balls_4_Down, 0) AS Playoff_4_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_4_Down, 0) / NULLIF(bat.Playoff_Balls_4_Down, 0) * 100, 2) AS Playoff_4_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_4_Down, 0) / NULLIF(bat.Playoff_Dismissals_4_Down, 0), 2) AS Playoff_4_Down_Average,
    COALESCE(bat.Playoff_Innings_5_Down, 0) AS Playoff_5_Down_Innings,
    COALESCE(bat.Playoff_Runs_5_Down, 0) AS Playoff_5_Down_Runs,
    COALESCE(bat.Playoff_Balls_5_Down, 0) AS Playoff_5_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_5_Down, 0) / NULLIF(bat.Playoff_Balls_5_Down, 0) * 100, 2) AS Playoff_5_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_5_Down, 0) / NULLIF(bat.Playoff_Dismissals_5_Down, 0), 2) AS Playoff_5_Down_Average,
    COALESCE(bat.Playoff_Innings_6_Down, 0) AS Playoff_6_Down_Innings,
    COALESCE(bat.Playoff_Runs_6_Down, 0) AS Playoff_6_Down_Runs,
    COALESCE(bat.Playoff_Balls_6_Down, 0) AS Playoff_6_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_6_Down, 0) / NULLIF(bat.Playoff_Balls_6_Down, 0) * 100, 2) AS Playoff_6_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_6_Down, 0) / NULLIF(bat.Playoff_Dismissals_6_Down, 0), 2) AS Playoff_6_Down_Average,
    COALESCE(bat.Playoff_Innings_7_Down, 0) AS Playoff_7_Down_Innings,
    COALESCE(bat.Playoff_Runs_7_Down, 0) AS Playoff_7_Down_Runs,
    COALESCE(bat.Playoff_Balls_7_Down, 0) AS Playoff_7_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_7_Down, 0) / NULLIF(bat.Playoff_Balls_7_Down, 0) * 100, 2) AS Playoff_7_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_7_Down, 0) / NULLIF(bat.Playoff_Dismissals_7_Down, 0), 2) AS Playoff_7_Down_Average,
    COALESCE(bat.Playoff_Innings_8_Down, 0) AS Playoff_8_Down_Innings,
    COALESCE(bat.Playoff_Runs_8_Down, 0) AS Playoff_8_Down_Runs,
    COALESCE(bat.Playoff_Balls_8_Down, 0) AS Playoff_8_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_8_Down, 0) / NULLIF(bat.Playoff_Balls_8_Down, 0) * 100, 2) AS Playoff_8_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_8_Down, 0) / NULLIF(bat.Playoff_Dismissals_8_Down, 0), 2) AS Playoff_8_Down_Average,
    COALESCE(bat.Playoff_Innings_9_Down, 0) AS Playoff_9_Down_Innings,
    COALESCE(bat.Playoff_Runs_9_Down, 0) AS Playoff_9_Down_Runs,
    COALESCE(bat.Playoff_Balls_9_Down, 0) AS Playoff_9_Down_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_9_Down, 0) / NULLIF(bat.Playoff_Balls_9_Down, 0) * 100, 2) AS Playoff_9_Down_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_9_Down, 0) / NULLIF(bat.Playoff_Dismissals_9_Down, 0), 2) AS Playoff_9_Down_Average,
    COALESCE(bat.Playoff_Innings_Top_Order, 0) AS Playoff_Top_Order_Innings,
    COALESCE(bat.Playoff_Runs_Top_Order, 0) AS Playoff_Top_Order_Runs,
    COALESCE(bat.Playoff_Balls_Top_Order, 0) AS Playoff_Top_Order_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_Top_Order, 0) / NULLIF(bat.Playoff_Balls_Top_Order, 0) * 100, 2) AS Playoff_Top_Order_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_Top_Order, 0) / NULLIF(bat.Playoff_Dismissals_Top_Order, 0), 2) AS Playoff_Top_Order_Average,
    COALESCE(bat.Playoff_Innings_Middle_Order, 0) AS Playoff_Middle_Order_Innings,
    COALESCE(bat.Playoff_Runs_Middle_Order, 0) AS Playoff_Middle_Order_Runs,
    COALESCE(bat.Playoff_Balls_Middle_Order, 0) AS Playoff_Middle_Order_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_Middle_Order, 0) / NULLIF(bat.Playoff_Balls_Middle_Order, 0) * 100, 2) AS Playoff_Middle_Order_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_Middle_Order, 0) / NULLIF(bat.Playoff_Dismissals_Middle_Order, 0), 2) AS Playoff_Middle_Order_Average,
    COALESCE(bat.Playoff_Innings_Late_Order, 0) AS Playoff_Late_Order_Innings,
    COALESCE(bat.Playoff_Runs_Late_Order, 0) AS Playoff_Late_Order_Runs,
    COALESCE(bat.Playoff_Balls_Late_Order, 0) AS Playoff_Late_Order_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_Late_Order, 0) / NULLIF(bat.Playoff_Balls_Late_Order, 0) * 100, 2) AS Playoff_Late_Order_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_Late_Order, 0) / NULLIF(bat.Playoff_Dismissals_Late_Order, 0), 2) AS Playoff_Late_Order_Average,
    COALESCE(bat.Playoff_Innings_Tail_Order, 0) AS Playoff_Tail_Order_Innings,
    COALESCE(bat.Playoff_Runs_Tail_Order, 0) AS Playoff_Tail_Order_Runs,
    COALESCE(bat.Playoff_Balls_Tail_Order, 0) AS Playoff_Tail_Order_Balls,
    ROUND(COALESCE(bat.Playoff_Runs_Tail_Order, 0) / NULLIF(bat.Playoff_Balls_Tail_Order, 0) * 100, 2) AS Playoff_Tail_Order_Strike_Rate,
    ROUND(COALESCE(bat.Playoff_Runs_Tail_Order, 0) / NULLIF(bat.Playoff_Dismissals_Tail_Order, 0), 2) AS Playoff_Tail_Order_Average,

    -- Playoff Bowling
    FLOOR(COALESCE(bowl.Playoff_Balls_Bowled, 0) / 6) + (MOD(COALESCE(bowl.Playoff_Balls_Bowled, 0), 6) / 10.0) AS Playoff_Overs_Bowled,
    COALESCE(bowl.Playoff_Runs_Conceded, 0) AS Playoff_Runs_Conceded,
    COALESCE(bowl.Playoff_Wickets, 0) AS Playoff_Wickets,
    ROUND(COALESCE(bowl.Playoff_Runs_Conceded, 0) / NULLIF(bowl.Playoff_Wickets, 0), 2) AS Playoff_Bowling_Average,
    ROUND(COALESCE(bowl.Playoff_Runs_Conceded, 0) / NULLIF((bowl.Playoff_Balls_Bowled / 6.0), 0), 2) AS Playoff_Economy_Rate,
    COALESCE(bowl.Playoff_Maidens, 0) AS Playoff_Maidens,
    COALESCE(bowl.Playoff_5_Wicket_Hauls, 0) AS Playoff_5_Wicket_Hauls,
    COALESCE(bowl.Playoff_Wides, 0) AS Playoff_Wides,
    COALESCE(bowl.Playoff_No_Balls, 0) AS Playoff_No_Balls,
    COALESCE(bowl.Playoff_Dot_Balls, 0) AS Playoff_Dot_Balls,
    
    -- Playoff Fielding
    COALESCE(fld.Playoff_Catches, 0) AS Playoff_Catches,
    COALESCE(fld.Playoff_WK_Catches, 0) AS Playoff_WK_Catches,
    COALESCE(fld.Playoff_Stumpings, 0) AS Playoff_Stumpings,
    COALESCE(fld.Playoff_Run_Outs, 0) AS Playoff_Run_Outs,
    
    -- Playoff Points
    COALESCE(pts.Playoff_Batting_Pts, 0) AS Playoff_Batting_Pts,
    COALESCE(pts.Playoff_Bowling_Pts, 0) AS Playoff_Bowling_Pts,
    COALESCE(pts.Playoff_Fielding_Pts, 0) AS Playoff_Fielding_Pts,
    COALESCE(pts.Playoff_Bonus_Pts, 0) AS Playoff_Bonus_Pts,
    COALESCE(pts.Playoff_Total_Pts, 0) AS Playoff_Total_Pts,

    -- === 4. PRACTICE LEAGUE BLOCK ===
    dp.IS_PRACTICE_LEAGUE AS Active_In_Practice_League,
    COALESCE(g.Practice_Games_Played, 0) AS Practice_Games_Played,
    COALESCE(bat.Practice_Runs, 0) AS Practice_Runs,
    COALESCE(bat.Practice_Balls_Faced, 0) AS Practice_Balls_Faced,
    ROUND(COALESCE(bat.Practice_Runs, 0) / NULLIF(bat.Practice_Balls_Faced, 0) * 100, 2) AS Practice_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs, 0) / NULLIF(bat.Practice_Times_Dismissed, 0), 2) AS Practice_Batting_Average,
    COALESCE(bat.Practice_30s, 0) AS Practice_30s,
    COALESCE(bat.Practice_50s, 0) AS Practice_50s,
    COALESCE(bat.Practice_75s, 0) AS Practice_75s,
    COALESCE(bat.Practice_100s, 0) AS Practice_100s,
    COALESCE(bat.Practice_4s, 0) AS Practice_4s,
    COALESCE(bat.Practice_6s, 0) AS Practice_6s,

    -- DYNAMIC POSITION SPLITS (FINAL SELECT - PRACTICE)
    COALESCE(bat.Practice_Innings_Opener, 0) AS Practice_Opener_Innings,
    COALESCE(bat.Practice_Runs_Opener, 0) AS Practice_Opener_Runs,
    COALESCE(bat.Practice_Balls_Opener, 0) AS Practice_Opener_Balls,
    ROUND(COALESCE(bat.Practice_Runs_Opener, 0) / NULLIF(bat.Practice_Balls_Opener, 0) * 100, 2) AS Practice_Opener_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_Opener, 0) / NULLIF(bat.Practice_Dismissals_Opener, 0), 2) AS Practice_Opener_Average,
    COALESCE(bat.Practice_Innings_1_Down, 0) AS Practice_1_Down_Innings,
    COALESCE(bat.Practice_Runs_1_Down, 0) AS Practice_1_Down_Runs,
    COALESCE(bat.Practice_Balls_1_Down, 0) AS Practice_1_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_1_Down, 0) / NULLIF(bat.Practice_Balls_1_Down, 0) * 100, 2) AS Practice_1_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_1_Down, 0) / NULLIF(bat.Practice_Dismissals_1_Down, 0), 2) AS Practice_1_Down_Average,
    COALESCE(bat.Practice_Innings_2_Down, 0) AS Practice_2_Down_Innings,
    COALESCE(bat.Practice_Runs_2_Down, 0) AS Practice_2_Down_Runs,
    COALESCE(bat.Practice_Balls_2_Down, 0) AS Practice_2_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_2_Down, 0) / NULLIF(bat.Practice_Balls_2_Down, 0) * 100, 2) AS Practice_2_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_2_Down, 0) / NULLIF(bat.Practice_Dismissals_2_Down, 0), 2) AS Practice_2_Down_Average,
    COALESCE(bat.Practice_Innings_3_Down, 0) AS Practice_3_Down_Innings,
    COALESCE(bat.Practice_Runs_3_Down, 0) AS Practice_3_Down_Runs,
    COALESCE(bat.Practice_Balls_3_Down, 0) AS Practice_3_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_3_Down, 0) / NULLIF(bat.Practice_Balls_3_Down, 0) * 100, 2) AS Practice_3_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_3_Down, 0) / NULLIF(bat.Practice_Dismissals_3_Down, 0), 2) AS Practice_3_Down_Average,
    COALESCE(bat.Practice_Innings_4_Down, 0) AS Practice_4_Down_Innings,
    COALESCE(bat.Practice_Runs_4_Down, 0) AS Practice_4_Down_Runs,
    COALESCE(bat.Practice_Balls_4_Down, 0) AS Practice_4_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_4_Down, 0) / NULLIF(bat.Practice_Balls_4_Down, 0) * 100, 2) AS Practice_4_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_4_Down, 0) / NULLIF(bat.Practice_Dismissals_4_Down, 0), 2) AS Practice_4_Down_Average,
    COALESCE(bat.Practice_Innings_5_Down, 0) AS Practice_5_Down_Innings,
    COALESCE(bat.Practice_Runs_5_Down, 0) AS Practice_5_Down_Runs,
    COALESCE(bat.Practice_Balls_5_Down, 0) AS Practice_5_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_5_Down, 0) / NULLIF(bat.Practice_Balls_5_Down, 0) * 100, 2) AS Practice_5_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_5_Down, 0) / NULLIF(bat.Practice_Dismissals_5_Down, 0), 2) AS Practice_5_Down_Average,
    COALESCE(bat.Practice_Innings_6_Down, 0) AS Practice_6_Down_Innings,
    COALESCE(bat.Practice_Runs_6_Down, 0) AS Practice_6_Down_Runs,
    COALESCE(bat.Practice_Balls_6_Down, 0) AS Practice_6_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_6_Down, 0) / NULLIF(bat.Practice_Balls_6_Down, 0) * 100, 2) AS Practice_6_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_6_Down, 0) / NULLIF(bat.Practice_Dismissals_6_Down, 0), 2) AS Practice_6_Down_Average,
    COALESCE(bat.Practice_Innings_7_Down, 0) AS Practice_7_Down_Innings,
    COALESCE(bat.Practice_Runs_7_Down, 0) AS Practice_7_Down_Runs,
    COALESCE(bat.Practice_Balls_7_Down, 0) AS Practice_7_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_7_Down, 0) / NULLIF(bat.Practice_Balls_7_Down, 0) * 100, 2) AS Practice_7_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_7_Down, 0) / NULLIF(bat.Practice_Dismissals_7_Down, 0), 2) AS Practice_7_Down_Average,
    COALESCE(bat.Practice_Innings_8_Down, 0) AS Practice_8_Down_Innings,
    COALESCE(bat.Practice_Runs_8_Down, 0) AS Practice_8_Down_Runs,
    COALESCE(bat.Practice_Balls_8_Down, 0) AS Practice_8_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_8_Down, 0) / NULLIF(bat.Practice_Balls_8_Down, 0) * 100, 2) AS Practice_8_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_8_Down, 0) / NULLIF(bat.Practice_Dismissals_8_Down, 0), 2) AS Practice_8_Down_Average,
    COALESCE(bat.Practice_Innings_9_Down, 0) AS Practice_9_Down_Innings,
    COALESCE(bat.Practice_Runs_9_Down, 0) AS Practice_9_Down_Runs,
    COALESCE(bat.Practice_Balls_9_Down, 0) AS Practice_9_Down_Balls,
    ROUND(COALESCE(bat.Practice_Runs_9_Down, 0) / NULLIF(bat.Practice_Balls_9_Down, 0) * 100, 2) AS Practice_9_Down_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_9_Down, 0) / NULLIF(bat.Practice_Dismissals_9_Down, 0), 2) AS Practice_9_Down_Average,
    COALESCE(bat.Practice_Innings_Top_Order, 0) AS Practice_Top_Order_Innings,
    COALESCE(bat.Practice_Runs_Top_Order, 0) AS Practice_Top_Order_Runs,
    COALESCE(bat.Practice_Balls_Top_Order, 0) AS Practice_Top_Order_Balls,
    ROUND(COALESCE(bat.Practice_Runs_Top_Order, 0) / NULLIF(bat.Practice_Balls_Top_Order, 0) * 100, 2) AS Practice_Top_Order_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_Top_Order, 0) / NULLIF(bat.Practice_Dismissals_Top_Order, 0), 2) AS Practice_Top_Order_Average,
    COALESCE(bat.Practice_Innings_Middle_Order, 0) AS Practice_Middle_Order_Innings,
    COALESCE(bat.Practice_Runs_Middle_Order, 0) AS Practice_Middle_Order_Runs,
    COALESCE(bat.Practice_Balls_Middle_Order, 0) AS Practice_Middle_Order_Balls,
    ROUND(COALESCE(bat.Practice_Runs_Middle_Order, 0) / NULLIF(bat.Practice_Balls_Middle_Order, 0) * 100, 2) AS Practice_Middle_Order_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_Middle_Order, 0) / NULLIF(bat.Practice_Dismissals_Middle_Order, 0), 2) AS Practice_Middle_Order_Average,
    COALESCE(bat.Practice_Innings_Late_Order, 0) AS Practice_Late_Order_Innings,
    COALESCE(bat.Practice_Runs_Late_Order, 0) AS Practice_Late_Order_Runs,
    COALESCE(bat.Practice_Balls_Late_Order, 0) AS Practice_Late_Order_Balls,
    ROUND(COALESCE(bat.Practice_Runs_Late_Order, 0) / NULLIF(bat.Practice_Balls_Late_Order, 0) * 100, 2) AS Practice_Late_Order_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_Late_Order, 0) / NULLIF(bat.Practice_Dismissals_Late_Order, 0), 2) AS Practice_Late_Order_Average,
    COALESCE(bat.Practice_Innings_Tail_Order, 0) AS Practice_Tail_Order_Innings,
    COALESCE(bat.Practice_Runs_Tail_Order, 0) AS Practice_Tail_Order_Runs,
    COALESCE(bat.Practice_Balls_Tail_Order, 0) AS Practice_Tail_Order_Balls,
    ROUND(COALESCE(bat.Practice_Runs_Tail_Order, 0) / NULLIF(bat.Practice_Balls_Tail_Order, 0) * 100, 2) AS Practice_Tail_Order_Strike_Rate,
    ROUND(COALESCE(bat.Practice_Runs_Tail_Order, 0) / NULLIF(bat.Practice_Dismissals_Tail_Order, 0), 2) AS Practice_Tail_Order_Average,

    -- Practice Bowling
    FLOOR(COALESCE(bowl.Practice_Balls_Bowled, 0) / 6) + (MOD(COALESCE(bowl.Practice_Balls_Bowled, 0), 6) / 10.0) AS Practice_Overs_Bowled,
    COALESCE(bowl.Practice_Runs_Conceded, 0) AS Practice_Runs_Conceded,
    COALESCE(bowl.Practice_Wickets, 0) AS Practice_Wickets,
    ROUND(COALESCE(bowl.Practice_Runs_Conceded, 0) / NULLIF(bowl.Practice_Wickets, 0), 2) AS Practice_Bowling_Average,
    ROUND(COALESCE(bowl.Practice_Runs_Conceded, 0) / NULLIF((bowl.Practice_Balls_Bowled / 6.0), 0), 2) AS Practice_Economy_Rate,
    COALESCE(bowl.Practice_Maidens, 0) AS Practice_Maidens,
    COALESCE(bowl.Practice_5_Wicket_Hauls, 0) AS Practice_5_Wicket_Hauls,
    COALESCE(bowl.Practice_Wides, 0) AS Practice_Wides,
    COALESCE(bowl.Practice_No_Balls, 0) AS Practice_No_Balls,
    COALESCE(bowl.Practice_Dot_Balls, 0) AS Practice_Dot_Balls,
    
    -- Practice Fielding
    COALESCE(fld.Practice_Catches, 0) AS Practice_Catches,
    COALESCE(fld.Practice_WK_Catches, 0) AS Practice_WK_Catches,
    COALESCE(fld.Practice_Stumpings, 0) AS Practice_Stumpings,
    COALESCE(fld.Practice_Run_Outs, 0) AS Practice_Run_Outs,
    
    -- Practice Points
    COALESCE(pts.Practice_Batting_Pts, 0) AS Practice_Batting_Pts,
    COALESCE(pts.Practice_Bowling_Pts, 0) AS Practice_Bowling_Pts,
    COALESCE(pts.Practice_Fielding_Pts, 0) AS Practice_Fielding_Pts,
    COALESCE(pts.Practice_Bonus_Pts, 0) AS Practice_Bonus_Pts,
    COALESCE(pts.Practice_Total_Pts, 0) AS Practice_Total_Pts,

    -- === 5. MOTM AWARDS ===
    COALESCE(motm.Career_MOTM_Awards, 0) AS Career_MOTM_Awards,
    COALESCE(motm.RS_MOTM_Awards, 0) AS RS_MOTM_Awards,
    COALESCE(motm.Playoff_MOTM_Awards, 0) AS Playoff_MOTM_Awards,
    COALESCE(motm.Practice_MOTM_Awards, 0) AS Practice_MOTM_Awards,

    -- === 6. LEAGUE AWARDS ===
    COALESCE(awd.Career_League_Awards, 'None') AS Career_League_Awards

FROM DIM_PLAYER dp
LEFT JOIN Games_Agg g ON dp.PLAYER_NAME = g.Player_Name
LEFT JOIN Batting_Agg bat ON dp.PLAYER_NAME = bat.Player_Name
LEFT JOIN Bowling_Agg bowl ON dp.PLAYER_NAME = bowl.Player_Name
LEFT JOIN Fielding_Agg fld ON dp.PLAYER_NAME = fld.Player_Name
LEFT JOIN Points_Agg pts ON dp.PLAYER_NAME = pts.Player_Name
LEFT JOIN MOTM_Agg motm ON dp.PLAYER_NAME = motm.Player_Name
LEFT JOIN Awards_Agg awd ON dp.PLAYER_NAME = awd.Player_Name;